"""
Take a screenshot of the Ticket Bifurcation section and post to Slack.
Uses simple file upload via old API + webhook fallback.
"""
import os
import sys
import json
import requests
from datetime import datetime

# --- Config ---
DASHBOARD_URL = "https://pft-daily-ticket.vercel.app"
SECTION_ID = "categorySection"
SCREENSHOT_PATH = "ticket_bifurcation.png"

SELECTED_CATEGORIES = [
    "Internet Issues",
    "Others",
    "Shifting Request",
    "Partner Misbehavior",
]

SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_WEBHOOK_URL = os.environ.get("SLACK_WEBHOOK_URL", "")
SLACK_CHANNEL = os.environ.get("SLACK_CHANNEL", "")


def take_screenshot():
    """Use Playwright to screenshot the Ticket Bifurcation section."""
    from playwright.sync_api import sync_playwright

    print("[Slack] Opening dashboard for screenshot...")
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1400, "height": 900})

        page.goto(DASHBOARD_URL, wait_until="networkidle", timeout=60000)
        page.wait_for_timeout(5000)

        section = page.locator(f"#{SECTION_ID}")
        section.wait_for(state="visible", timeout=30000)

        # Apply filter
        print(f"[Slack] Applying filter: {SELECTED_CATEGORIES}")
        selected_json = json.dumps(SELECTED_CATEGORIES)
        page.evaluate(f"""() => {{
            const selectedCats = {selected_json};
            document.querySelectorAll('#pivotDropdown input[data-cat]').forEach(cb => {{
                cb.checked = false;
            }});
            document.querySelectorAll('#pivotDropdown input[data-cat]').forEach(cb => {{
                const catName = cb.getAttribute('data-cat');
                if (selectedCats.includes(catName)) {{
                    cb.checked = true;
                }}
            }});
            const total = document.querySelectorAll('#pivotDropdown input[data-cat]').length;
            const checked = document.querySelectorAll('#pivotDropdown input[data-cat]:checked').length;
            const btn = document.querySelector('#pivotFilterBtn');
            if (btn) btn.innerHTML = '&#9776; Filter Categories <sup>(' + checked + '/' + total + ')</sup> &#9660;';
            if (typeof filterPivotTable === 'function') filterPivotTable();
        }}""")
        page.wait_for_timeout(1000)

        section.scroll_into_view_if_needed()
        page.wait_for_timeout(500)

        section.screenshot(path=SCREENSHOT_PATH)
        browser.close()

    print(f"[Slack] Screenshot saved: {SCREENSHOT_PATH}")
    return SCREENSHOT_PATH


def upload_to_slack(image_path):
    """Upload screenshot using the simple files.upload API."""
    today = datetime.now().strftime("%Y-%m-%d")
    message = f"<!here> Please review the pending tickets as of today that are currently under action by the PFT team.\n\n:bar_chart: *PFT Daily Ticket Bifurcation Report — {today}*\n\nView full dashboard: {DASHBOARD_URL}"

    # Method 1: Try simple files.upload (works for both public and private channels)
    if SLACK_BOT_TOKEN and SLACK_CHANNEL:
        print("[Slack] Uploading via files.upload API...")
        try:
            with open(image_path, "rb") as f:
                resp = requests.post(
                    "https://slack.com/api/files.upload",
                    headers={"Authorization": f"Bearer {SLACK_BOT_TOKEN}"},
                    data={
                        "channels": SLACK_CHANNEL,
                        "initial_comment": message,
                        "title": f"Ticket Bifurcation - {today}",
                        "filename": f"ticket_bifurcation_{today}.png",
                    },
                    files={"file": ("ticket_bifurcation.png", f, "image/png")}
                )
            data = resp.json()
            if data.get("ok"):
                print("[Slack] Screenshot posted successfully!")
                return True
            else:
                print(f"[Slack] files.upload failed: {data.get('error', data)}")
        except Exception as e:
            print(f"[Slack] Upload error: {e}")

    # Method 2: Try posting image via webhook with base64 (text fallback)
    print("[Slack] Falling back to webhook with dashboard link...")
    if SLACK_WEBHOOK_URL:
        payload = {
            "text": message + "\n\n_Auto-generated by PFT Agent_"
        }
        resp = requests.post(SLACK_WEBHOOK_URL, json=payload)
        if resp.status_code == 200:
            print("[Slack] Webhook notification sent successfully!")
            return True
        else:
            print(f"[Slack] Webhook failed: {resp.status_code} {resp.text}")

    return False


if __name__ == "__main__":
    try:
        img_path = take_screenshot()
        upload_to_slack(img_path)
    except Exception as e:
        print(f"[Slack] Error: {e}")
        # Last resort: send failure via webhook
        today = datetime.now().strftime("%Y-%m-%d")
        if SLACK_WEBHOOK_URL:
            requests.post(SLACK_WEBHOOK_URL, json={
                "text": f":x: *PFT Daily Update Failed — {today}*\nPlease run manually via Claude Code."
            })
        sys.exit(1)
